# Generated by Django 3.2.7 on 2021-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('greeting', '가입인사'), ('question', '질문'), ('information', '정보')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
