# Generated by Django 3.2.7 on 2021-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210904_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
